// alert('Hello world!');
// const name = prompt('Введите ваше имя:'); 
// const lastName = prompt('Введите вашу фамилию:');
// const greeting = 'Hello, ' + name + ' ' + lastName + '!';
// alert(greeting);
// const x = 22;
// let q = (x == 22);
// alert(q);
// alert(2 + '3');
// alert(3 - '2');
const a = Number(prompt('Введите число A'));
const b = Number(prompt('Введите число B'));
const c = Number(prompt('Введите число C'));
alert((a + b + c) / 3);
alert((a * b * c) ** (1 / 3));
